server.port=8099
spring.application.name=task-api

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=taskapidb

spring.data.mongodb.auto-index-creation=true
jwt.secret=super_secret_key_for_task_api_project_very_long_key
jwt.expiration=36000000


